/*******************************************************************************
BLiT
Stephen Niedzielski [sniedzie@digipen.edu]
Created:  Saturday, November 24, 2007 [Stephen Niedzielski]
Modified: Saturday, November 24, 2007 [Stephen Niedzielski]
*******************************************************************************/


/****************** Includes. ******************/
#include "Global.h"

/* init_adc source generated by MicroAPL CFInit. */
void init_adc (void)
{
    /* Scan mode = Triggered sequential 
       ADC clock frequency = 5.00 MHz 
       Voltage reference supplied by VREFH and VREFL 
       All ADC interrupts disabled 
         
       Sample list: 
           Sample 0 : AN0 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 1 : AN1 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 2 : AN2 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 3 : AN3 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 4 : AN4 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 5 : AN5 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 6 : AN6 
                      Low limit = $000, High limit = $FFF, Offset = $000 
           Sample 7 : AN7 
                      Low limit = $000, High limit = $FFF, Offset = $000 
    */

    /* Initialise LOLIM, HILIM and OFFST registers of enabled channels: */
    MCF_ADC_ADLLMT0 = 0;
    MCF_ADC_ADHLMT0 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS0 = 0;
    MCF_ADC_ADLLMT1 = 0;
    MCF_ADC_ADHLMT1 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS1 = 0;
    MCF_ADC_ADLLMT2 = 0;
    MCF_ADC_ADHLMT2 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS2 = 0;
    MCF_ADC_ADLLMT3 = 0;
    MCF_ADC_ADHLMT3 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS3 = 0;
    MCF_ADC_ADLLMT4 = 0;
    MCF_ADC_ADHLMT4 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS4 = 0;
    MCF_ADC_ADLLMT5 = 0;
    MCF_ADC_ADHLMT5 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS5 = 0;
    MCF_ADC_ADLLMT6 = 0;
    MCF_ADC_ADHLMT6 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS6 = 0;
    MCF_ADC_ADLLMT7 = 0;
    MCF_ADC_ADHLMT7 = MCF_ADC_ADHLMT_HLMT(0xfff);
    MCF_ADC_ADOFS7 = 0;

    /* Initialise ADC */
    MCF_ADC_ADZCC = 0;
    MCF_ADC_ADLST1 = MCF_ADC_ADLST1_SAMPLE3(0x3) |
                     MCF_ADC_ADLST1_SAMPLE2(0x2) |
                     MCF_ADC_ADLST1_SAMPLE1(0x1);
    MCF_ADC_ADLST2 = MCF_ADC_ADLST2_SAMPLE7(0x7) |
                     MCF_ADC_ADLST2_SAMPLE6(0x6) |
                     MCF_ADC_ADLST2_SAMPLE5(0x5) |
                     MCF_ADC_ADLST2_SAMPLE4(0x4);
    MCF_ADC_ADSDIS = 0;
    MCF_ADC_CAL = 0x4000;
    MCF_ADC_CTRL1 = MCF_ADC_CTRL1_STOP0 |
                    MCF_ADC_CTRL1_SMODE(0x4);
    MCF_ADC_CTRL2 = MCF_ADC_CTRL2_STOP1 |
                    MCF_ADC_CTRL2_DIV(0x2);

    /* Power up ADC converter(s) in use */
    MCF_ADC_POWER = MCF_ADC_POWER_PUDELAY(0xd) |
                    MCF_ADC_POWER_PD2;

    /* Wait for converter A power up to complete */
    while (MCF_ADC_POWER & MCF_ADC_POWER_PSTS0)
        ;

    /* Wait for converter B power up to complete */
    while (MCF_ADC_POWER & MCF_ADC_POWER_PSTS1)
        ;
}
